#!/usr/bin/env ruby
require 'find'
require 'net/http'
require 'uri'
require 'digest/sha1'
require 'json'
require 'fileutils'

@command = ARGV[0]
@pkgName = ARGV[1]

CREVOS_PRE = '/usr/local'
CREVOS_COM_PATH = CREVOS_PRE + '/bin/crevos'
CREVOS_LIB_PATH = CREVOS_PRE + '/lib/crevos/'
CREVOS_CONFIG_PATH = CREVOS_PRE + '/etc/crevos/'
CREVOS_BREW_PATH = CREVOS_PRE + '/tmp/crevos/'
CREVOS_DEST_PATH = CREVOS_BREW_PATH + '/dest'

$LOAD_PATH.unshift "#{CREVOS_LIB_PATH}lib"

USER = `whoami`.chomp

system "sudo chmod +x /usr/local/bin/crevos"
system "sudo chmod +x /usr/local/bin/crevos-reinstall"
system "sudo chmod +x /usr/local/bin/crevos-uninstall"

@device = JSON.parse(File.read(CREVOS_CONFIG_PATH + 'device.json'), symbolize_names: true)
#symbolize also values
@device.each do |key, elem|
  @device[key] = @device[key].to_sym rescue @device[key]
end

def setPkg (pkgName, silent = false)
  require CREVOS_LIB_PATH + 'packages/' + pkgName
  @pkg = Object.const_get(pkgName.capitalize)
  @pkg.name = pkgName
  puts "Found #{pkgName}, version #{@pkg.version}" unless silent
end

def list_packages
  numberss = 0
  numbersss = 0
  puts "Installed = (i)"
  Find.find (CREVOS_LIB_PATH + 'packages') do |filename|
    Find.find(CREVOS_CONFIG_PATH + 'meta/') do |packageList|
        packageName = File.basename filename, '.rb'
        print '(i) ' if packageList == CREVOS_CONFIG_PATH + 'meta/' + packageName + '.filelist' || (packageName == "Superpack" && numberss == 0) || (packageName == "buildessential" && numbersss == 0)
        numberss = 1 if packageName == "allDepend"
        numbersss = 1 if packageName == "buildessential"
    end
    puts File.basename filename, '.rb' if File.extname(filename) == '.rb'
  end
end

def search (pkgName, silent = false)
  Find.find (CREVOS_LIB_PATH + 'packages') do |filename|
    return setPkg(pkgName, silent) if filename == CREVOS_LIB_PATH + 'packages/' + pkgName + '.rb'
  end
  abort "package #{pkgName} not found :("
end

def update
  abort "'Crevos update' is used to update crevos itself. Use 'crevos upgrade <packageName> to upgrade a specific package." if @pkgName

  #update package lists
  Dir.chdir CREVOS_LIB_PATH do
    system "git fetch origin master"
    system "git reset --hard origin/master"
  end
  puts "Package lists, crevos, and library updated."
  
  #check for outdated installed packages
  puts "Checking for package updates..."
  puts ""

  canBeUpdated = 0
  @device[:installed_packages].each do |package|
    search package[:name], true
    if package[:version] != @pkg.version
      canBeUpdated += 1
      puts @pkg.name + " could be updated from " + package[:version] + " to " + @pkg.version
    end
  end
  
  if canBeUpdated > 0
    puts "\nRun 'crevos upgrade' to upgrade everything or 'crevos upgrade <packageName>' to upgrade a specific package."
  else
    puts "Your software is up to date :<)"
  end
end

def upgrade
  if @pkgName
    search @pkgName

    currentVersion = nil
    @device[:installed_packages].each do |package|
      if package[:name] == @pkg.name
        currentVersion = package[:version]
      end
    end
    
    if currentVersion != @pkg.version
      search @pkg.name
      puts "Updating #{@pkg.name}..."
      remove 
      resolveDependenciesAndInstall
    else
      puts "#{@pkg.name} is already up to date."
    end
  else
    toBeUpdated = []
    @device[:installed_packages].each do |package|
      search package[:name], true
      if package[:version] != @pkg.version
        toBeUpdated.push(package[:name])
      end
    end
  
    if toBeUpdated.length > 0
      puts "Updating packages..."
      toBeUpdated.each do |package|
        search package
        remove
        resolveDependenciesAndInstall
      end
      puts "Packages have been updated."
    else
      puts "Your software is already up to date."
    end
  end
end

def download
  if @pkg.binary_url && @pkg.binary_url.has_key?(@device[:architecture])
    url = @pkg.binary_url[@device[:architecture]]
    source = false
    puts "Precompiled binary available, downloading..."
  else
    url = @pkg.source_url
    source = true
    puts "No precompiled binary available for your platform, downloading source..."
  end
  uri = URI.parse url
  filename = File.basename(uri.path)
  if source
    sha1sum = @pkg.source_sha1
  else
    sha1sum = @pkg.binary_sha1[@device[:architecture]]
  end
  Dir.chdir CREVOS_BREW_PATH do
    system('wget', '--continue', '--content-disposition', '--no-check-certificate', '-N', url, '-O', filename)
    abort 'Checksum mismatch :/ try again' unless Digest::SHA1.hexdigest( File.read("./#{filename}") ) == sha1sum
  end
  puts "Archive downloaded"
  return {source: source, filename: filename}
end

def resolveDependenciesAndInstall
  begin
    origin = @pkg.name

    resolveDependencies
  
    search origin
    install
  rescue InstallError => e 
    puts "#{@pkg.name} failed to install: #{e.to_s}"
  ensure
    #cleanup
    unless ARGV[2] == 'keep'
      Dir.chdir CREVOS_BREW_PATH do
        system "sudo rm -rf *"
        system "sudo mkdir dest" #this is a little ugly, feel free to find a better way
      end
    end
  end
end

def resolveDependencies
  @dependencies = []

  def pushDeps
    if @pkg.dependencies
      @dependencies.unshift @pkg.dependencies
      
      @pkg.dependencies.each do |dep|
        search dep, true
        pushDeps
      end
    end
  end
  
  pushDeps
  
  return if @dependencies.empty?

  puts "Following packages also need to be installed: "
  
  @dependencies.flatten!.uniq!
  @dependencies.each do |dep|
    print dep + " "
  end
  
  puts ""
  puts "Do you agree? [Y/n]"
  response = STDIN.getc
  case response
  when "n"
    abort "No changes made."
  when "\n", "y", "Y"
    puts "Proceeding..."
    proceed = true
  else
    puts "I don't understand '#{response}' :("
    abort "No changes made."
  end

  if proceed
    @dependencies.each do |dep|
      search dep
      install
    end
  end
end

def install
  if @device[:installed_packages].any? { |pkg| pkg[:name] == @pkg.name }
    puts "Package #{@pkg.name} already installed, skipping..."
    return
  end

  unless @pkg.is_fake?
    meta = download
    Dir.chdir CREVOS_BREW_PATH do
      puts "Unpacking archive, this may take a while..."
      system "tar", "xf", meta[:filename]
      if meta[:source] == true
        abort "You don't have a working C compiler. Run 'crevos install buildessential' to get one and try again." unless system("gcc", "--version")
        topdir = `tar -tf #{meta[:filename]} | sed -e 's@/.*@@' | uniq`.chomp!
        Dir.chdir CREVOS_BREW_PATH + topdir do
          puts "Building from source, this may take a while..."
          @pkg.build
          system "rm -rf", CREVOS_DEST_PATH + "/*" #wipe crevos destdir
          puts "Preconfiguring package..."
          @pkg.install
        end

        Dir.chdir CREVOS_DEST_PATH do
          #create directory list
          system "find . -type f > ../filelist"
          system "find . -type l >> ../filelist"
          system "cut -c2- ../filelist > filelist"
          #create file list
          system "find . -type d > ../dlist"
          system "cut -c2- ../dlist > dlistcut"
          system "tail -n +2 dlistcut > dlist"
          #remove temporary files
          system "rm dlistcut ../dlist ../filelist"
          
          #create resulting folders list
          directories = []
          Dir.glob('*').select do |fn|
            if File.directory?(fn)
              directories.push(fn)
            end
          end

          #wipe directories with the same name in brew dir to avoid conflicts
          directories.each do |dir|
            system "rm -rf ../" + dir.chomp
          end

          #move result files and directories to brew dir
          system "mv * ../"
        end
      end

      puts "Installing..."

      FileUtils.mv 'dlist', CREVOS_CONFIG_PATH + "meta/#{@pkg.name}.directorylist"
      FileUtils.mv 'filelist', CREVOS_CONFIG_PATH + "meta/#{@pkg.name}.filelist"
 
      File.open(CREVOS_CONFIG_PATH + "meta/#{@pkg.name}.directorylist").each_line do |line|
        system "sudo", "mkdir", "-p", line.chomp
      end

      File.open(CREVOS_CONFIG_PATH + "meta/#{@pkg.name}.filelist").each_line do |line|
        system "sudo", "mv", CREVOS_BREW_PATH + line.chomp, line.chomp
      end
    end
  end
  
  #add to installed packages
  @device[:installed_packages].push(name: @pkg.name, version: @pkg.version)
  File.open(CREVOS_CONFIG_PATH + 'device.json', 'w') do |file|
    output = JSON.parse @device.to_json
    file.write JSON.pretty_generate(output)
  end
  puts "#{@pkg.name.capitalize} installed!"
end

def remove
  unless @device[:installed_packages].any? { |pkg| pkg[:name] == @pkg.name }
    puts "Package #{@pkg.name} isn't installed."
    return
  end
  
  unless @pkg.is_fake?
    Dir.chdir CREVOS_CONFIG_PATH do
      File.open("meta/#{@pkg.name}.filelist").each_line do |line|
        begin
          File.unlink line.chomp
        rescue => exception #swallow exception
        end
      end
  
      File.readlines("meta/#{@pkg.name}.directorylist").reverse.each do |line|
        begin
          Dir.rmdir line.chomp
        rescue => exception #swallow exception
        end
      end

      File.unlink "meta/#{@pkg.name}.filelist"
      File.unlink "meta/#{@pkg.name}.directorylist"
    end
  end

def updategrade
  system "sudo chmod +x " + CREVOS_COM_PATH
  update
  system "sudo chmod +x " + CREVOS_COM_PATH
  upgrade
  system "sudo chmod +x " + CREVOS_COM_PATH
end

def reinstall
  system "sudo chmod +x " + CREVOS_COM_PATH
  remove
  system "sudo chmod +x " + CREVOS_COM_PATH
  install
  system "sudo chmod +x " + CREVOS_COM_PATH
  resolveDependenciesAndInstall
end

def helps
  puts "Available commands .Arg amount."
  puts "  download .1."
  puts "  reinstall .1."
  puts "  search .1."
  puts "  update .1."
  puts "  upgrade .1."
  puts "  updategrade .0."
  puts "  help .0."
  puts "done"
end

def uninstall
  if "all" == @pkgName
    system "sudo rm " + CREVOS_COM_PATH
    system "sudo rm -rf " + CREVOS_LIB_PATH
    system "sudo rm -rf " + CREVOS_CONFIG_PATH
    system "sudo rm -rf " + CREVOS_BREW_PATH
  end
end

def crevos_uninstall
    system "sudo rm " + CREVOS_COM_PATH
    system "sudo rm -rf " + CREVOS_LIB_PATH
    system "sudo rm -rf " + CREVOS_CONFIG_PATH
    system "sudo rm -rf " + CREVOS_BREW_PATH
    echo "Crevos uninstalled sucessfully"
end

  #remove from installed packages
  @device[:installed_packages].each do |elem|
    @device[:installed_packages].delete elem if elem[:name] == @pkg.name
  end
  File.open(CREVOS_CONFIG_PATH + 'device.json', 'w') do |file|
    out = JSON.parse @device.to_json
    file.write JSON.pretty_generate(out)
  end
  puts "#{@pkg.name.capitalize} removed!"
end

case @command
when "search"
  if @pkgName
    search @pkgName
  else
    list_packages
  end
  system "sudo chmod +x " + CREVOS_COM_PATH
when "download"
  search @pkgName
  download
  system "sudo chmod +x " + CREVOS_COM_PATH
when "reinstall"
  reinstall
  system "sudo chmod +x " + CREVOS_COM_PATH
when "help"
  helps
  system "sudo chmod +x " + CREVOS_COM_PATH
when "update"
  update
  system "sudo chmod +x " + CREVOS_COM_PATH
when "upgrade"
  upgrade
  system "sudo chmod +x " + CREVOS_COM_PATH
when "install"
  search @pkgName
  resolveDependenciesAndInstall
  system "sudo chmod +x " + CREVOS_COM_PATH
when "remove"
  abort 'Removing actions must be ran with sudo.' unless USER == 'root'
  search @pkgName
  remove
  system "sudo chmod +x " + CREVOS_COM_PATH
when "updategrade"
  updategrade
  system "sudo chmod +x " + CREVOS_COM_PATH
when "uninstall-all"
  crevos_uninstall
  system "sudo chmod +x " + CREVOS_COM_PATH
when "reinstall-all"
  crevos_uninstall
  system "sudo chmod +x " + CREVOS_COM_PATH
  system "wget -q -O - https://raw.github.com/CodeBuds/Crevos/master/install.sh | bash"
  system "sudo chmod +x " + CREVOS_COM_PATH
when nil
  puts "Crevos, version 0.0.59"
  puts "Usage: crevos [command] [package]"
  puts "Available commands: search, download, install, remove, help, updategrade, reinstall"
  system "sudo chmod +x " + CREVOS_COM_PATH
else
  puts "Crevos doesn't have an idea how to do #{@command} :("
  puts "Available commands: search, download, install, remove, help, updategrade, reinstall"
  system "sudo chmod +x " + CREVOS_COM_PATH
end


